package main

import (
	"go-tour/errors"
	"go-tour/methods"
	more_types "go-tour/more-types"
	"go-tour/readers"
	"go-tour/utils"
)

func main() {
	utils.Title("Hello")
	hello()
	utils.Title("Sandbox")
	sandbox()
	utils.Title("Packages")
	packages()
	utils.Title("Functions")
	functions()
	utils.Title("Variables")
	variables()
	utils.Title("Types")
	types()
	utils.Title("Constants")
	constants()
	utils.Title("For loops")
	forLoop()
	utils.Title("If")
	ifs()
	utils.Title("Exercices: Loops and functions")
	exerciceLoopsAndFunctions()
	utils.Title("Switch")
	switches()
	utils.Title("Defer")
	defers()
	utils.Title("Miscellaneous")
	misc()
	utils.Title("Types")
	moreTypes()
	utils.Title("Exercise: Slices")
	exerciceSlices()
	utils.Title("Maps")
	maps()
	utils.Title("Exercice: Maps")
	exerciceMaps()
	utils.Title("Function values and closures")
	functionValuesClosures()
	utils.Title("Exercice: Fibonacci closure")
	fibonacciClosure()
	utils.Title("Methods")
	methods.Main()
	utils.Title("Types manipulation")
	more_types.Main()
	utils.Title("Exercice: Stringer")
	exerciceStringer()
	utils.Title("Errors")
	errors.Main()
	utils.Title("Exercice: Errors")
	exerciceErrors()
	utils.Title("Readers")
	readers.Main()
	utils.Title("Exercice: Readers")
	exerciceReaders()
	utils.Title("Exercice: rot13Reader")
	exerciceRot13Reader()
}
